### PR TITLE
Fix #2: Skip downloads if pip is correct version

### LINKED ISSUE #2: Skip download if pip already at pip version
I'm using pipstrap in CI which caches the virtualenv. There's no need to download pip 8.0.2 every time (along with the other deps). I think pipstrap should check `pip --version` to see if it matches the version to be installed and bail out if so. Thoughts?

I'm happy to file a PR if you agree.

### PR DESCRIPTION
**Pull request by pmclanahan**
Decided to go ahead and file the PR just in case you liked the idea.

Thanks again for pipstrap Erik! It's been a massive time saver for us.

### CODE REVIEW

**Comment by pmclanahan** [comment]
Rebased on current master. Any thoughts on this @erikrose ?

**Comment by erikrose** [comment]
In the last week, I have realized just how deep the packaging rabbit hole goes. Since shipping peep with Let's Encrypt, I've been a party to bug after bug [in pip](https://github.com/letsencrypt/letsencrypt/issues/2588#issue-137758855) and friends (which I see, since peep emits bug-reporting instructions), to the point where I no longer trust shipping anything but a fully pinned trio of pip, [setuptools](https://github.com/letsencrypt/letsencrypt/pull/2599), and wheel and installing into an empty virtualenv [with the wheel cache off](https://github.com/erikrose/letsencrypt/commit/70beb0bd3b8be70927c2c705a22ff69adc8cb374). At the very least, I then can reproduce reported bugs. (In fact, I'm conflicted about the "if" around argparse.) If we could check the versions of all of the packages pipstrap cares about (`pip list`?), I'd be into that. What do you think?

**Comment by pmclanahan** [comment]
My thought here was simply that if the environment already has a pip at the current version, then we can assume that pipstrap had been previously run successfully. I'm just using it as a proxy. If you think this will introduce bugs and maintenance overhead for you then I'm happy to work around this in my own deployment scripts. My goal was simply to make this a bit faster and require no network in situations when this gets run every time (e.g. CI) but sometimes the venv was cached and downloading these packages again is superfluous.

**Comment by erikrose** [comment]
Sorry for the long wait, pmac. I've subsumed this into #9.

**Pull request closed without merging**
